import { IAdapter } from '../adapter/IAdapter';
import { Container } from '../container/Container';
import { IProxiedRoute } from '../proxy/IProxiedRoute';
import { IRouteRequest } from '../request/IRouteRequest';
import { SendErrorFunction } from './SendErrorFunction';
import { SendResponseFunction } from './SendResponseFunction';
import { RequestHandler } from './composition/RequestHandler';

export interface IMaestro extends Container {

	/**
	 * Api Call Resolver
	 * ------------------
	 * 
	 * Handles how the controller method will be called
	 * 
	 * Call resolver has access to:
	 * 1. ApiRoute - The route properties, with all of its proxies
	 * 2. ApiRequest - The request (generated by an adapter)
	 * 3. SendResponse - A function given by the adapter to send a response 
	 * to the caller
	 * 4. SendError - A function, given by the adapter, to send a error response
	 * to the caller 
	 * 
	 * @param resolver 
	 */
	setRequestHandler(resolver: RequestHandler): void;


	/**
	 * Handle
	 * ------
	 * 
	 * Function exposed to all adapters that receives 
	 */
	handle(
		route: IProxiedRoute,
		request: IRouteRequest,
		sendResponse: SendResponseFunction,
		sendError: SendErrorFunction,
	): void;

	addAdapter(adapter: IAdapter): void;

	start(): void;

}